import type { Metadata } from "next";
import { Rochester, Poppins } from "next/font/google";
import "./globals.css";

export const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const rochester = Rochester({
  variable: "--font-rochester",
  weight: "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} font-sans ${rochester.variable} bg-background`}>
        
        {children}
      </body>
    </html>
  );
}
